package seals

import (
	_ "embed"
	_ "image/png"
)

var (
	//go:embed  00.png
	SunPng []byte
	//go:embed  01.png
	DragonPng []byte
	//go:embed  02.png
	WindPng []byte
	//go:embed  03.png
	NightPng []byte
	//go:embed  04.png
	SeedPng []byte
	//go:embed  05.png
	SerpentPng []byte
	//go:embed  06.png
	WorldBridgerPng []byte
	//go:embed  07.png
	HandPng []byte
	//go:embed  08.png
	StarPng []byte
	//go:embed  09.png
	MoonPng []byte
	//go:embed  10.png
	DogPng []byte
	//go:embed  11.png
	MonkeyPng []byte
	//go:embed  12.png
	HumanPng []byte
	//go:embed  13.png
	SkyWalkerPng []byte
	//go:embed  14.png
	WizzardPng []byte
	//go:embed  15.png
	EaglePng []byte
	//go:embed  16.png
	WarriorPng []byte
	//go:embed  17.png
	EarthPng []byte
	//go:embed  18.png
	MirrorPng []byte
	//go:embed  19.png
	StormPng []byte
)
